# ===== LOCAL (�nico perfil) =====
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hospital
quarkus.datasource.username=hospital_user
quarkus.datasource.password=hospital_pass

# gerar o schema a partir das entidades em cada start (apaga e recria)
quarkus.hibernate-orm.database.generation=update

# logs �teis
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.http.port=8080

# Salvar o schema OpenAPI gerado durante o build
quarkus.smallrye-openapi.store-schema-directory=target/openapi

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type,Origin,X-Requested-With
quarkus.http.cors.exposed-headers=Location,Content-Disposition